# NumPy Exercises for Data Analysis

# Importing Lib

In [1]:
import numpy as np

# How to create a 1D array?

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# How to create a boolean array?

In [3]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# How to extract items that satisfy a given condition from 1D array?

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

# How to replace items that satisfy a condition with another value in numpy array?

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[arr%2!=0] = -1

In [9]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# How to replace items that satisfy a condition without affecting the original array?

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
out = np.where(arr%2!=0, -1, arr)

In [12]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# How to reshape an array?

In [14]:
arr = np.arange(10)

In [15]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
arr.reshape(2, -1) # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# How to stack two arrays vertically?

In [17]:
a = np.arange(10).reshape(2, -1)

In [18]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
b = np.repeat(1, 10).reshape(2, -1)

In [20]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.concatenate([a,b], axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# How to stack two arrays horizontally?

In [24]:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [25]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [26]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# How to generate custom sequences in numpy without hardcoding?

In [27]:
a = np.array([1, 2, 3])

In [28]:
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# How to get the common items between two python numpy arrays?

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [30]:
np.intersect1d(a,b)

array([2, 4])

# How to remove from one array those items that exist in another?

In [31]:
a = np.array([1, 2, 3, 4, 5])

In [32]:
b = np.array([5, 6, 7, 8, 9])

In [33]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

# How to get the positions where elements of two arrays match?

In [34]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [35]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

# How to extract all numbers between a given range from a numpy array?

In [36]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [37]:
a[np.where((a>=5) & (a<=10))]

array([ 6,  9, 10])

In [38]:
a[np.where(np.logical_and(a>=5, a<=10))]

array([ 6,  9, 10])

In [39]:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

# How to make a python function that handles scalars to work on numpy arrays?

In [40]:
def maxx(x,y):
    if x >= y:
        return x
    else:
        return y

In [41]:
pair_max = np.vectorize(maxx, otypes=[float])

In [42]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 5])

In [43]:
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

# How to swap two columns in a 2d numpy array?

In [44]:
arr = np.arange(9).reshape(3,3)

In [45]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
arr[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# How to swap two rows in a 2d numpy array?

In [47]:
arr = np.arange(9).reshape(3,3)

In [48]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
arr[[1, 0, 2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# How to reverse the rows of a 2D array?

In [50]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# How to reverse the columns of a 2D array?

In [51]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# How to create a 2D array containing random floats between 5 and 10?

In [52]:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))

In [53]:
rand_arr

array([[6.73604386, 6.2782952 , 8.61198528],
       [5.82918138, 7.58773828, 5.39901538],
       [6.62978542, 7.45684316, 7.03307721],
       [5.12801216, 6.04561718, 6.92128893],
       [9.77797278, 5.93216633, 7.03782966]])

In [54]:
rand_arr = np.random.uniform(5,10, size=(5,3))

In [55]:
rand_arr

array([[9.52182105, 6.76219948, 7.98338271],
       [8.13082158, 5.05818707, 9.56104208],
       [5.61662841, 5.46387505, 9.00654655],
       [7.80609273, 5.25478144, 7.45640427],
       [8.56759249, 7.54377854, 9.14497212]])

# How to print only 3 decimal places in python numpy array?

In [56]:
rand_arr = np.random.random([5,3])

In [57]:
rand_arr

array([[0.50010951, 0.04382266, 0.35885728],
       [0.21828886, 0.61586218, 0.28853197],
       [0.18902558, 0.07487907, 0.73808092],
       [0.98711209, 0.00158991, 0.99291444],
       [0.28554777, 0.66439913, 0.9460923 ]])

In [58]:
np.set_printoptions(precision=3)

In [59]:
rand_arr

array([[0.5  , 0.044, 0.359],
       [0.218, 0.616, 0.289],
       [0.189, 0.075, 0.738],
       [0.987, 0.002, 0.993],
       [0.286, 0.664, 0.946]])

In [60]:
rand_arr[:4]

array([[0.5  , 0.044, 0.359],
       [0.218, 0.616, 0.289],
       [0.189, 0.075, 0.738],
       [0.987, 0.002, 0.993]])

# How to limit the number of items printed in output of numpy array?

In [61]:
a = np.arange(15)

In [62]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
np.set_printoptions(threshold=6)

In [64]:
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [65]:
import sys

In [66]:
np.set_printoptions(threshold=sys.maxsize)

In [67]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [68]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [69]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

# How to extract a particular column from 1D array of tuples?

In [70]:
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


In [71]:
species = np.array([row[4] for row in iris_1d])

In [72]:
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')