# Importing Lib

In [1]:
import numpy as np

# How to create a 1D array?

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# How to create a boolean array?

In [3]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# How to extract items that satisfy a given condition from 1D array?

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

# How to replace items that satisfy a condition with another value in numpy array?

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[arr%2!=0] = -1

In [9]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# How to replace items that satisfy a condition without affecting the original array?

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
out = np.where(arr%2!=0, -1, arr)

In [12]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# How to reshape an array?

In [14]:
arr = np.arange(10)

In [15]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
arr.reshape(2, -1) # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# How to stack two arrays vertically?

In [17]:
a = np.arange(10).reshape(2, -1)

In [18]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
b = np.repeat(1, 10).reshape(2, -1)

In [20]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.concatenate([a,b], axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# How to stack two arrays horizontally?

In [24]:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [25]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [26]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# How to generate custom sequences in numpy without hardcoding?

In [27]:
a = np.array([1, 2, 3])

In [28]:
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# How to get the common items between two python numpy arrays?

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [30]:
np.intersect1d(a,b)

array([2, 4])