# NumPy Arrays

In [1]:
my_list = [1, 2, 3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = ([1,2,3], [4,5,6], [7,8,9])

In [7]:
my_mat

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array Attributes

In [9]:
print('Dimension ', arr.ndim)
print('Shape ', arr.shape)
print('Size ', arr.size)
print('Type ', arr.dtype)
print('Itemsize', arr.itemsize)
print('Bytes ', arr.nbytes)

Dimension  1
Shape  (3,)
Size  3
Type  int32
Itemsize 4
Bytes  12


# NumPy Arange

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

# Zeros

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# Ones

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Linspace

In [17]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# Identity Matrix

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random Numbers

In [19]:
np.random.rand(5)

array([0.6544009 , 0.49709578, 0.24600247, 0.49740069, 0.59163694])

In [20]:
np.random.rand(2,2)

array([[0.57109243, 0.79604148],
       [0.20602943, 0.22779608]])

In [21]:
np.random.randn(2)

array([ 0.08851623, -0.40984845])

In [22]:
np.random.randn(2,3)

array([[-0.72952047, -0.46173246, -1.64502817],
       [ 0.82762867,  0.56619126,  3.03997446]])

In [23]:
np.random.randint(1, 100, 10)

array([69, 40, 30, 40, 24, 97, 65, 97, 67,  7])

# Reshape

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0, 50, 10)

In [27]:
ranarr

array([ 2, 15, 45, 12, 14, 42, 23, 10,  7, 16])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Useful Operations

In [29]:
ranarr.max()

45

In [30]:
ranarr.min()

2

In [31]:
ranarr.argmax()

2

In [32]:
ranarr.argmin()

0

In [33]:
np.random.normal(0, 1, (3,3))

array([[-0.8574063 ,  0.07039103,  0.89869173],
       [ 0.77309258, -1.75426194, -1.94521128],
       [-1.34836396, -0.0532969 , -1.6380815 ]])

In [34]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [35]:
np.zeros(10, dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.ones((3,5),dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.empty(3)

array([1., 1., 1.])

In [38]:
np.full((3,5), 3.2)

array([[3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2]])