# Mathematical Functions

In [1]:
import numpy as np

In [2]:
theta =  np.linspace(0, np.pi, 3)

In [3]:
theta

array([0.        , 1.57079633, 3.14159265])

In [4]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [5]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [6]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [7]:
x = [-1, 0, 1]

In [8]:
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [9]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [10]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

In [11]:
x = [1, 2, 3]

In [12]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [13]:
np.exp2(x)

array([2., 4., 8.])

In [14]:
np.power(3, x)

array([ 3,  9, 27], dtype=int32)

In [15]:
x = [1, 2, 4, 10]

In [16]:
np.log(x)

array([0.        , 0.69314718, 1.38629436, 2.30258509])

In [17]:
np.log2(x)

array([0.        , 1.        , 2.        , 3.32192809])

In [18]:
np.log10(x)

array([0.        , 0.30103   , 0.60205999, 1.        ])

In [19]:
x = [0, 0.001, 0.01, 0.1]

In [20]:
print("exp(x) - 1", np.expm1(x))

exp(x) - 1 [0.         0.0010005  0.01005017 0.10517092]


In [21]:
print("log(1+x)  ", np.log1p(x))

log(1+x)   [0.         0.0009995  0.00995033 0.09531018]


In [22]:
x = np.arange(1,6)

In [23]:
x

array([1, 2, 3, 4, 5])

In [24]:
np.add.reduce(x)

15

In [25]:
np.multiply.reduce(x)

120

In [26]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [27]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [28]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [29]:
x = np.array([1, 2, 3])

In [30]:
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [31]:
x

array([1, 2, 3])

In [32]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [33]:
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [34]:
y = np.array([[99],
              [99]])

In [35]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])